# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{memflash}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vladimir Andrijevik"]
  s.date = %q{2010-09-14}
  s.description = %q{Memflash is a gem which enables storing really long values in the Rails FlashHash without writing them to the session. Instead, it transparently uses `Rails.cache`, thus enabling the flash in your actions to contain large values, and still fit in a cookie-based session store}
  s.email = %q{vladimir@zendesk.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "lib/memflash.rb",
     "memflash.gemspec",
     "test/memflash_test.rb",
     "test/rails/app/controllers/application.rb",
     "test/rails/config/boot.rb",
     "test/rails/config/environment.rb",
     "test/rails/config/environments/test.rb",
     "test/rails/config/routes.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/zendesk/memflash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Memflash is a gem which enables storing really long values in the Rails FlashHash without writing them to the session}
  s.test_files = [
    "test/memflash_test.rb",
     "test/rails/app/controllers/application.rb",
     "test/rails/config/boot.rb",
     "test/rails/config/environment.rb",
     "test/rails/config/environments/test.rb",
     "test/rails/config/routes.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ">= 2.3.6", "< 3.3")
    else
      s.add_dependency(%q<actionpack>, ">= 2.3.6", "< 3.3")
    end
  else
    s.add_dependency(%q<actionpack>, ">= 2.3.6", "< 3.3")
  end
end

