name: test
on:
  # This being an open source project, we want pull requests from branches on a
  # forked repo to run actions on *our* fork. So we run on pull request events,
  # and on pushes to (our) master branch (i.e. merges).
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
          - gemfiles/rails7.1.gemfile
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby-version }}
    - name: test ${{ matrix.ruby-version }} with ${{ matrix.gemfile }}
      run: |
        bundle exec rake test

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests passed"
          else
            echo "Some tests failed"
            false
          fi
