name: test
on:
  # This being an open source project, we want pull requests from branches on a
  # forked repo to run actions on *our* fork. So we run on pull request events,
  # and on pushes to (our) master branch (i.e. merges).
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    name: test
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        rvm:
          - 2.6
          - 2.7
        gemfile:
          - gemfiles/rails5.1.gemfile
          - gemfiles/rails5.2.gemfile
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
        exclude:
          - {rvm: 2.6, gemfile: gemfiles/rails7.0.gemfile}
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.rvm }}
    - name: test ${{ matrix.rvm }} with ${{ matrix.gemfile }}
      run: |
        bundle exec rake test
